apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::135719648897:role/eksServiceRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::135719648897:user/Quang.Nguyen@daugherty.com
      username: arn:aws:iam::135719648897:user/Quang.Nguyen@daugherty.com
      groups:
        - system:masters
    - userarn: arn:aws:iam::135719648897:user/Alex.Champsaur@daugherty.com
      username: arn:aws:iam::135719648897:user/Alex.Champsaur@daugherty.com
      groups:
        - system:masters
    - userarn: arn:aws:iam::135719648897:user/Lauren.Griffith@daugherty.com
      username: arn:aws:iam::135719648897:user/Lauren.Griffith@daugherty.com
      groups:
        - system:masters
