apiVersion: v1
kind: Pod
metadata:
  name: kaniko-aws
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=./Dockerfile",
            "--context=s3://kaniko-aws/context.tar.gz",
            "--destination=135719648897.dkr.ecr.us-east-1.amazonaws.com/cox_bb:kaniko"]
    volumeMounts:
      - name: aws-secret
        mountPath: /root/.aws/
      - name: docker-config
        mountPath: /kaniko/.docker/
  restartPolicy: Never
  volumes:
    - name: aws-secret
      secret:
        secretName: aws-secret
    - name: docker-config
      configMap:
        name: docker-config
