# Service
apiVersion: v1
kind: Service
metadata:
   name: redis-service
   labels:
     app: redis-service
spec:
   ports:
   - port: 8080
     targetPort: 8080
     name: http
     protocol: TCP
   selector:
     app: redis-service


---
# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-service
  labels:
    app: redis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-service
  template:
    metadata:
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-service
        image: 135719648897.dkr.ecr.us-east-1.amazonaws.com/redis-service:7ca45ea
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 15
        env:
        - name: REDIS_SERVER
          value: rejson:6379
      imagePullSecrets:
      - name: redis-aws-secret
      
