apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-service-account
  namespace: veo

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: veo
  name: secret-creator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets","serviceaccounts"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---
# This role binding allows "eks-service-account" to create secrets in the "dev" namespace.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: create-secrets
  namespace: veo
subjects:
- kind: ServiceAccount
  name: redis-service-account # Name is case sensitive
  namespace: veo
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-creator
  apiGroup: rbac.authorization.k8s.io